version: "3"
services:
  db:
    image: postgres:14
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recsys_db
    networks:
      - recsys_net
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3

  backend:
    build: Dockerfile
    container_name: backend
    environment:
      HOST: database
      PORT: 5432
      DB: recsys_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:8000/test"]
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

networks:
  recsys_net:
    name: recsys_net